[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "is-none"
version = "1.0.0"
description = "A tiny utility to test whether a value is exactly None."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.13"

keywords = ["none", "utility", "tiny"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/rogep/is-none"
Repository = "https://github.com/rogep/is-none"
"Bug Tracker" = "https://github.com/rogep/is-none/issues"


[dependency-groups]
dev = [
  "hatch>=1.16.2",
  "mypy>=1.17.1",
  "pre-commit>=4.3.0",
  "pytest>=8.4.2",
  "ruff>=0.14.0",
  "twine>=6.2.0",
]


[tool.hatch.build]
packages = ["is_none"]


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-q"
testpaths = ["tests"]


[tool.mypy]
ignore_missing_imports = true


[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["E203", "E266", "E501", "UP040"]
select = ["E", "F", "I", "UP", "B"]
